# Generated by Django 5.0.3 on 2024-12-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressorapk', '0002_uplodedimage_resized_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplodedimage',
            name='converted_image',
            field=models.ImageField(blank=True, null=True, upload_to='converted_folder/'),
        ),
    ]
